apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: http://172.16.0.78:8888/admin1/edge1-config
    branch: main
    auth: token
    secretRef:
      name: gitea-token
    period: 30s