apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: provisioningrequests.o2ims.oran.org
spec:
  group: o2ims.oran.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              clusterName:
                type: string
              nodeCount:
                type: integer
              region:
                type: string
              resourcePool:
                type: string
          status:
            type: object
            properties:
              phase:
                type: string
              message:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: provisioningrequests
    singular: provisioningrequest
    kind: ProvisioningRequest
    shortNames:
    - pr
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deploymentmanagers.o2ims.oran.org
spec:
  group: o2ims.oran.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              oCloudId:
                type: string
              serviceUri:
                type: string
          status:
            type: object
            properties:
              state:
                type: string
              lastHeartbeat:
                type: string
  scope: Namespaced
  names:
    plural: deploymentmanagers
    singular: deploymentmanager
    kind: DeploymentManager
    shortNames:
    - dm
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcepools.o2ims.oran.org
spec:
  group: o2ims.oran.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              location:
                type: string
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  storage:
                    type: string
          status:
            type: object
            properties:
              capacity:
                type: object
              allocated:
                type: object
              available:
                type: object
  scope: Namespaced
  names:
    plural: resourcepools
    singular: resourcepool
    kind: ResourcePool
    shortNames:
    - rp