apiVersion: apps/v1
kind: Deployment
metadata:
  name: o2ims-controller
  namespace: o2ims-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: o2ims-controller
  template:
    metadata:
      labels:
        app: o2ims-controller
    spec:
      containers:
      - name: controller
        image: python:3.9-slim
        command:
        - "sh"
        - "-c"
        - |
          pip install --no-cache-dir flask && cat > /app.py << 'EOF'
          from flask import Flask, jsonify
          import datetime
          app = Flask(__name__)

          @app.route('/')
          def home():
              return jsonify({
                  "name": "O2IMS API",
                  "version": "1.0.0",
                  "status": "operational",
                  "timestamp": datetime.datetime.utcnow().isoformat() + "Z"
              })

          @app.route('/health')
          def health():
              return jsonify({"status": "healthy"})

          @app.route('/o2ims-api/v1/ims')
          def ims_info():
              return jsonify({
                  "ims_id": "edge1-o2ims",
                  "name": "Edge1 O2IMS Instance",
                  "description": "O2IMS for edge1 cluster",
                  "serviceUrl": "http://172.16.4.45:31280",
                  "status": "ready"
              })

          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=8080)
          EOF
          python /app.py
        ports:
        - containerPort: 8080
          name: http