---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: 'alertmanager@nephio-demo.local'

    templates:
      - '/etc/alertmanager/templates/*.tmpl'

    route:
      group_by: ['alertname', 'site']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
        - match:
            severity: critical
          receiver: 'critical-alerts'
        - match:
            component: infrastructure
          receiver: 'infrastructure-alerts'
        - match:
            component: o2ims
          receiver: 'o2ims-alerts'

    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: 'http://localhost:5001/alerts'
            send_resolved: true

      - name: 'critical-alerts'
        webhook_configs:
          - url: 'http://localhost:5001/critical'
            send_resolved: true
            title: 'CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
            text: |
              {{ range .Alerts }}
              Alert: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              Site: {{ .Labels.site }}
              Severity: {{ .Labels.severity }}
              {{ end }}

      - name: 'infrastructure-alerts'
        webhook_configs:
          - url: 'http://localhost:5001/infrastructure'
            send_resolved: true

      - name: 'o2ims-alerts'
        webhook_configs:
          - url: 'http://localhost:5001/o2ims'
            send_resolved: true

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'site', 'component']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  default.tmpl: |
    {{ define "__subject" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}
    {{ end }}

    {{ define "__description" }}{{ end }}

    {{ define "__text_alert_list" }}{{ range . }}
    Alert: {{ .Annotations.summary }}
    Description: {{ .Annotations.description }}
    Site: {{ .Labels.site }}
    Component: {{ .Labels.component }}
    Severity: {{ .Labels.severity }}
    Time: {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
    {{ end }}{{ end }}

    {{ define "nephio.title" }}
    {{ if eq .Status "firing" }}🚨 {{ else }}✅ {{ end }}{{ .GroupLabels.alertname }} - {{ .GroupLabels.site }}
    {{ end }}

    {{ define "nephio.text" }}
    {{ if eq .Status "firing" }}
    **Firing Alerts:**
    {{ template "__text_alert_list" .Alerts.Firing }}
    {{ end }}
    {{ if eq .Status "resolved" }}
    **Resolved Alerts:**
    {{ template "__text_alert_list" .Alerts.Resolved }}
    {{ end }}
    {{ end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.25.0
        args:
          - '--config.file=/etc/alertmanager/alertmanager.yml'
          - '--storage.path=/alertmanager'
          - '--web.external-url=http://172.16.0.78:31093'
          - '--cluster.listen-address=0.0.0.0:9094'
        ports:
        - containerPort: 9093
        - containerPort: 9094
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: alertmanager-config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager-templates-volume
          mountPath: /etc/alertmanager/templates
        - name: alertmanager-storage-volume
          mountPath: /alertmanager
      volumes:
      - name: alertmanager-config-volume
        configMap:
          name: alertmanager-config
      - name: alertmanager-templates-volume
        configMap:
          name: alertmanager-templates
      - name: alertmanager-storage-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      nodePort: 31093
      protocol: TCP
    - name: cluster
      port: 9094
      targetPort: 9094
      protocol: TCP