apiVersion: tna.tna.ai/v1alpha1
kind: IntentDeployment
metadata:
  name: both-sites-deployment
  namespace: default
spec:
  intent: |
    {
      "service": "distributed-analytics",
      "sites": ["edge1", "edge2"],
      "replicas": {
        "edge1": 3,
        "edge2": 2
      },
      "resources": {
        "cpu": "500m",
        "memory": "1Gi"
      },
      "endpoints": {
        "edge1": {
          "o2ims": "http://172.16.4.45:31280",
          "monitoring": "http://172.16.4.45:30090"
        },
        "edge2": {
          "o2ims": "http://172.16.4.176:31280",
          "monitoring": "http://172.16.4.176:30090"
        }
      },
      "federation": {
        "enabled": true,
        "sync_interval": "30s"
      }
    }

  compileConfig:
    engine: kpt
    renderTimeout: 5m

  deliveryConfig:
    targetSite: both
    gitOpsRepo: https://github.com/thc1006/nephio-intent-to-o2-demo
    syncWaitTimeout: 15m

  gatesConfig:
    enabled: true
    sloThresholds:
      error_rate: "0.05"
      latency_p99: "500ms"
      availability: "99.0"
      cross_site_latency: "100ms"

  rollbackConfig:
    autoRollback: true
    maxRetries: 3
    retainFailedArtifacts: true