# Self-signed ClusterIssuer for cert-manager
# This is the minimal setup for testing - use proper CA in production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
# Alternative: CA ClusterIssuer with generated root certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: ca-root
  secretName: ca-root-secret
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-cluster-issuer
spec:
  ca:
    secretName: ca-root-secret