---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tna-tna-ai-v1alpha1-intentdeployment
  failurePolicy: Fail
  name: vintentdeployment.kb.io
  rules:
  - apiGroups:
    - tna.tna.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - intentdeployments
  sideEffects: None
