apiVersion: v1
kind: Secret
metadata:
  name: gitea-token
  namespace: config-management-system
type: Opaque
stringData:
  username: admin
  token: REPLACE_WITH_YOUR_GENERATED_TOKEN  # You need to replace this with actual token