apiVersion: v1
kind: ServiceAccount
metadata:
  name: o2ims-controller
  namespace: o2ims-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: o2ims-controller
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["o2ims.oran.org"]
  resources: ["provisioningrequests", "provisioningrequests/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["o2ims.oran.org"]
  resources: ["deploymentmanagers", "resourcepools", "resourcetypes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: o2ims-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: o2ims-controller
subjects:
- kind: ServiceAccount
  name: o2ims-controller
  namespace: o2ims-system