apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-reconciler
  namespace: config-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: root-reconciler
  template:
    metadata:
      labels:
        app: root-reconciler
    spec:
      serviceAccountName: root-reconciler
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        env:
        - name: GITSYNC_REPO
          value: "http://147.251.115.143:8888/admin1/edge1-config.git"
        - name: GITSYNC_BRANCH
          value: "main"
        - name: GITSYNC_ROOT
          value: "/repo"
        - name: GITSYNC_LINK
          value: "current"
        - name: GITSYNC_PERIOD
          value: "30s"
        - name: GITSYNC_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitea-token
              key: username
        - name: GITSYNC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-token
              key: token
        volumeMounts:
        - name: repo
          mountPath: /repo
      - name: reconciler
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          while true; do
            if [ -d "/repo/current/apps/intent" ]; then
              echo "[$(date)] Applying configurations from /apps/intent directory..."
              find /repo/current/apps/intent -name "*.yaml" -o -name "*.yml" | while read file; do
                echo "  Applying: $(basename $file)"
                kubectl apply -f "$file" 2>&1 | grep -v "unchanged" || true
              done
              echo "[$(date)] Sync complete"
            else
              echo "[$(date)] Waiting for /repo/current/apps/intent directory..."
              ls -la /repo/ 2>/dev/null || true
            fi
            sleep 30
          done
        volumeMounts:
        - name: repo
          mountPath: /repo
      volumes:
      - name: repo
        emptyDir: {}