apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

# Monitoring stack configurations for edge2 site

resources:
  - prometheus-config.yaml
  - grafana-config.yaml
  - alerting-rules.yaml
  - slo-monitoring.yaml

# Common labels for monitoring components
commonLabels:
  site: edge2
  component: monitoring
  managed-by: gitops

# ConfigMap generation for dashboards
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards.json
    options:
      disableNameSuffixHash: true

# Secret references (actual secrets managed externally)
secretGenerator:
  - name: monitoring-credentials
    literals:
      - grafana-admin-user=admin
    options:
      disableNameSuffixHash: true