apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-definitions
  namespace: monitoring
data:
  slos.yaml: |
    # SLO definitions for Edge2 site
    slos:
      - name: api-availability
        description: "API availability SLO for Edge2"
        target: 99.9
        window: 30d
        query: |
          sum(rate(http_requests_total{status!~"5..",site="edge2"}[5m]))
          /
          sum(rate(http_requests_total{site="edge2"}[5m]))

      - name: latency-p99
        description: "99th percentile latency SLO"
        target: 500  # milliseconds
        window: 7d
        query: |
          histogram_quantile(0.99,
            sum(rate(http_request_duration_seconds_bucket{site="edge2"}[5m])) by (le)
          ) * 1000

      - name: error-budget
        description: "Error budget for Edge2 services"
        target: 0.1  # 0.1% error rate
        window: 30d
        query: |
          sum(rate(http_requests_total{status=~"5..",site="edge2"}[5m]))
          /
          sum(rate(http_requests_total{site="edge2"}[5m]))
          * 100

---
apiVersion: v1
kind: Service
metadata:
  name: slo-gateway
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics/api/v1/slo"
    prometheus.io/port: "8081"
spec:
  type: ClusterIP
  selector:
    app: slo-gateway
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-gateway-config
  namespace: monitoring
data:
  config.yaml: |
    server:
      port: 8081
      site: edge2

    prometheus:
      url: http://prometheus:9090
      refresh_interval: 30s

    slo_endpoints:
      - path: /metrics/api/v1/slo
        format: json
      - path: /metrics/api/v1/slo/prometheus
        format: prometheus

    aggregation:
      enabled: true
      sites:
        - edge2
      metrics:
        - availability
        - latency_p50
        - latency_p95
        - latency_p99
        - error_rate
        - throughput