apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oran-nfs
resources:
  # Intent-generated network functions will be placed here
  # - cu-deployment.yaml
  # - du-deployment.yaml
