run:
  timeout: 5m
  tests: false

issues:
  exclude-dirs:
    - test
    - vendor
    - third_party

  exclude-files:
    - ".*_test\\.go$"

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo
        - lll
    - path: test/
      linters:
        - errcheck
        - goconst
        - gocyclo
        - lll

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gocyclo
    - lll
    - nakedret

linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 3
    min-occurrences: 2
  gocyclo:
    min-complexity: 25
  lll:
    line-length: 280