apiVersion: v1
kind: Namespace
metadata:
  name: slo-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service-v2
  namespace: slo-monitoring
  labels:
    app: echo-service-v2
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-service-v2
  template:
    metadata:
      labels:
        app: echo-service-v2
        version: v2
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo:0.2.3
        args:
        - "-text=SLO-Echo-Service-v2"
        - "-listen=:8080"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service-v2
  namespace: slo-monitoring
  labels:
    app: echo-service-v2
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: echo-service-v2