apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-embb-upf
  namespace: ran-slice-a
  labels:
    app: upf
    site-name: edge3
    intent-id: intent-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      containers:
      - name: upf
        image: 'nginx:alpine'
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: '1'
