apiVersion: workload.nephio.org/v1alpha1
kind: NetworkSlice
metadata:
  name: slice-intent-e2e-1757777411-edge3
  namespace: default
  labels:
    intent-id: intent-e2e-1757777411
    service-type: enhanced-mobile-broadband
    target-site: edge3
spec:
  sliceType: eMBB
  plmn:
    mcc: '001'
    mnc: '01'
  qos:
    5qi: 5
    gfbr: 1000Mbps
