kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: edge2
nodes:
- role: control-plane
  extraPortMappings:
  # HTTP ingress port
  - containerPort: 31080
    hostPort: 31080
    protocol: TCP
  # HTTPS ingress port
  - containerPort: 31443
    hostPort: 31443
    protocol: TCP
  # O2IMS API port
  - containerPort: 31280
    hostPort: 31280
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "site=edge2,environment=local"