apiVersion: v1
kind: Namespace
metadata:
  name: flagger-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flagger
  namespace: flagger-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flagger
rules:
- apiGroups: [""]
  resources: ["events", "configmaps", "secrets", "services", "pods"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["flagger.app"]
  resources: ["canaries", "canaries/status", "metrictemplates", "alertproviders"]
  verbs: ["*"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways", "httproutes"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flagger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flagger
subjects:
- kind: ServiceAccount
  name: flagger
  namespace: flagger-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
  namespace: flagger-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagger
  template:
    metadata:
      labels:
        app: flagger
    spec:
      serviceAccountName: flagger
      containers:
      - name: flagger
        image: ghcr.io/fluxcd/flagger:1.35.0
        ports:
        - name: http
          containerPort: 8080
        command:
        - ./flagger
        - -log-level=info
        - -metrics-server=http://prometheus.monitoring:9090
        - -mesh-provider=kubernetes
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: canaries.flagger.app
spec:
  group: flagger.app
  names:
    kind: Canary
    plural: canaries
    singular: canary
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: ["targetRef", "service", "analysis"]
            properties:
              targetRef:
                type: object
                required: ["apiVersion", "kind", "name"]
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
              progressDeadlineSeconds:
                type: integer
              service:
                type: object
                required: ["port"]
                properties:
                  port:
                    type: integer
                  targetPort:
                    type: integer
                  gateways:
                    type: array
                    items:
                      type: string
                  hosts:
                    type: array
                    items:
                      type: string
              skipAnalysis:
                type: boolean
              analysis:
                type: object
                properties:
                  interval:
                    type: string
                  threshold:
                    type: integer
                  maxWeight:
                    type: integer
                  stepWeight:
                    type: integer
                  stepWeightPromotion:
                    type: integer
                  metrics:
                    type: array
                    items:
                      type: object
                      required: ["name"]
                      properties:
                        name:
                          type: string
                        interval:
                          type: string
                        thresholdRange:
                          type: object
                          properties:
                            min:
                              type: number
                            max:
                              type: number
                        query:
                          type: string
                  webhooks:
                    type: array
                    items:
                      type: object
                      required: ["name", "url"]
                      properties:
                        name:
                          type: string
                        url:
                          type: string
                        timeout:
                          type: string
                        metadata:
                          type: object
                          additionalProperties:
                            type: string
          status:
            type: object
            properties:
              phase:
                type: string
              canaryWeight:
                type: integer
              failedChecks:
                type: integer
              iterations:
                type: integer