# Grafana Configuration for Multi-Site Monitoring Dashboard
# Displays metrics from Edge-1, Edge-2, and central orchestration

global:
  imageRegistry: ""

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: 9.4.0

  adminUser: admin
  adminPassword: nephio123!

  nodePort: 31300

  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard"

  # Environment variables for external datasources
  env:
    GF_SECURITY_ADMIN_PASSWORD: nephio123!
    GF_USERS_ALLOW_SIGN_UP: false
    GF_SECURITY_ALLOW_EMBEDDING: true
    GF_AUTH_ANONYMOUS_ENABLED: true
    GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer

  # Datasources pointing to both edge sites and local Prometheus
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus-Central
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          isDefault: true
          editable: false
          jsonData:
            timeInterval: 30s
            httpMethod: GET

        - name: Edge1-Direct
          type: prometheus
          access: proxy
          url: http://172.16.4.45:30091
          editable: false
          jsonData:
            timeInterval: 30s
            customQueryParameters: "site=edge1"

        - name: Edge2-Direct
          type: prometheus
          access: proxy
          url: http://172.16.4.176:30091
          editable: false
          jsonData:
            timeInterval: 30s
            customQueryParameters: "site=edge2"

  # Dashboard providers
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'multi-site-dashboards'
          orgId: 1
          folder: 'Multi-Site Monitoring'
          type: file
          disableDeletion: false
          updateIntervalSeconds: 30
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards

  # Pre-configured dashboards
  dashboards:
    multi-site-monitoring:
      multi-site-overview:
        gnetId: 12486
        revision: 1
        datasource: Prometheus-Central

      o2ims-monitoring:
        json: |
          {
            "dashboard": {
              "id": null,
              "title": "O2IMS Multi-Site Monitoring",
              "tags": ["o2ims", "multi-site"],
              "timezone": "browser",
              "panels": [
                {
                  "id": 1,
                  "title": "O2IMS Service Availability",
                  "type": "stat",
                  "targets": [
                    {
                      "expr": "up{service=\"o2ims\"}",
                      "legendFormat": "{{site}} O2IMS",
                      "refId": "A"
                    }
                  ],
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "thresholds"
                      },
                      "mappings": [
                        {
                          "options": {
                            "0": {
                              "text": "DOWN"
                            },
                            "1": {
                              "text": "UP"
                            }
                          },
                          "type": "value"
                        }
                      ],
                      "thresholds": {
                        "steps": [
                          {
                            "color": "red",
                            "value": null
                          },
                          {
                            "color": "green",
                            "value": 1
                          }
                        ]
                      }
                    }
                  },
                  "gridPos": {
                    "h": 6,
                    "w": 12,
                    "x": 0,
                    "y": 0
                  }
                }
              ],
              "time": {
                "from": "now-1h",
                "to": "now"
              },
              "refresh": "30s"
            }
          }

      slo-monitoring:
        json: |
          {
            "dashboard": {
              "id": null,
              "title": "SLO Multi-Site Dashboard",
              "tags": ["slo", "multi-site"],
              "timezone": "browser",
              "panels": [
                {
                  "id": 1,
                  "title": "SLO Service Health",
                  "type": "graph",
                  "targets": [
                    {
                      "expr": "up{service=\"slo-monitoring\"}",
                      "legendFormat": "{{site}} SLO Service",
                      "refId": "A"
                    }
                  ],
                  "gridPos": {
                    "h": 8,
                    "w": 24,
                    "x": 0,
                    "y": 0
                  },
                  "yAxes": [
                    {
                      "min": 0,
                      "max": 1,
                      "unit": "short"
                    }
                  ]
                },
                {
                  "id": 2,
                  "title": "Response Time 95th Percentile",
                  "type": "graph",
                  "targets": [
                    {
                      "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, site))",
                      "legendFormat": "{{site}} 95th percentile",
                      "refId": "A"
                    }
                  ],
                  "gridPos": {
                    "h": 8,
                    "w": 12,
                    "x": 0,
                    "y": 8
                  }
                },
                {
                  "id": 3,
                  "title": "Error Rate",
                  "type": "graph",
                  "targets": [
                    {
                      "expr": "(sum(rate(http_requests_total{status=~\"5..\"}[5m])) by (site) / sum(rate(http_requests_total[5m])) by (site)) * 100",
                      "legendFormat": "{{site}} Error Rate %",
                      "refId": "A"
                    }
                  ],
                  "gridPos": {
                    "h": 8,
                    "w": 12,
                    "x": 12,
                    "y": 8
                  }
                }
              ],
              "time": {
                "from": "now-1h",
                "to": "now"
              },
              "refresh": "30s"
            }
          }

      gitops-monitoring:
        json: |
          {
            "dashboard": {
              "id": null,
              "title": "GitOps Sync Status",
              "tags": ["gitops", "sync"],
              "timezone": "browser",
              "panels": [
                {
                  "id": 1,
                  "title": "GitOps Sync Status",
                  "type": "stat",
                  "targets": [
                    {
                      "expr": "gitops_sync_status",
                      "legendFormat": "{{repository}} sync status",
                      "refId": "A"
                    }
                  ],
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "thresholds"
                      },
                      "thresholds": {
                        "steps": [
                          {
                            "color": "red",
                            "value": null
                          },
                          {
                            "color": "green",
                            "value": 1
                          }
                        ]
                      }
                    }
                  },
                  "gridPos": {
                    "h": 6,
                    "w": 24,
                    "x": 0,
                    "y": 0
                  }
                }
              ],
              "time": {
                "from": "now-1h",
                "to": "now"
              },
              "refresh": "30s"
            }
          }

# Plugins for enhanced monitoring
plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - grafana-clock-panel
  - flant-statusmap-panel