# Example ProvisioningRequest for O-RAN/5G RAN deployment
# This represents a comprehensive O2 IMS ProvisioningRequest following
# O-RAN specifications and Nephio best practices
apiVersion: o2ims.oran.org/v1alpha1
kind: ProvisioningRequest
metadata:
  name: example-pr
  namespace: default
  labels:
    # O-RAN specific labels
    oran.org/deployment-type: "5g-ran"
    oran.org/vendor: "nephio-demo"
    oran.org/version: "v1.2.0"
    # Nephio labels for package management
    nephio.org/package-name: "o-ran-cu"
    nephio.org/blueprint: "cu-up-cu-cp"
    nephio.org/region: "us-west1"
  annotations:
    # Intent-based annotations
    intent.nephio.org/source: "tmf921-intent-12345"
    intent.nephio.org/created-by: "intent-gateway"
    # O2 IMS metadata
    o2ims.oran.org/deployment-id: "deployment-ran-001"
    o2ims.oran.org/smo-reference: "smo://nephio-demo/v1"
    description: |
      Provision a complete O-RAN Central Unit (CU) with both Control Plane (CU-CP) 
      and User Plane (CU-UP) functions for 5G RAN deployment in edge location.
      
      This includes:
      - CU-CP for RRC and PDCP control
      - CU-UP for PDCP user plane processing  
      - F1 interface towards Distributed Units (DUs)
      - E1 interface between CU-CP and CU-UP
      - Integration with SMO (Service Management and Orchestration)
spec:
  # Target cluster for deployment - edge cluster in this case
  targetCluster: "edge-cluster-us-west1-a"
  
  description: |
    Deploy O-RAN Central Unit functions (CU-CP and CU-UP) for 5G RAN.
    This deployment supports up to 1000 connected devices per cell with
    low-latency requirements for URLLC services and enhanced mobile broadband.
  
  # Resource requirements for O-RAN CU deployment
  resourceRequirements:
    # CPU: CU-CP needs significant processing for RRC and mobility management
    # CU-UP needs high throughput for user plane packet processing  
    cpu: "8000m"    # 8 CPU cores total
    
    # Memory: Large memory for user contexts, packet buffers, and control plane state
    memory: "16Gi"  # 16GB RAM
    
    # Storage: Persistent storage for configuration, logs, and temporary data
    storage: "50Gi" # 50GB persistent storage
    
    # Additional O-RAN specific requirements (would be extended in real implementation)
    # accelerators: "dpdk" # Data Plane Development Kit acceleration
    # hugepages: "2Gi"     # Large pages for packet processing performance
    # numa: "0,1"          # NUMA node affinity for performance

  # Network configuration for O-RAN interfaces
  networkConfig:
    # VLAN for O-RAN fronthaul/midhaul networks
    vlan: 100
    
    # Subnet for CU management network
    subnet: "10.0.100.0/24"
    
    # Gateway for external connectivity (to SMO, other RAN functions)
    gateway: "10.0.100.1"
    
    # Additional network interfaces would be configured here in real deployment:
    # f1Interface: "10.0.101.0/24"  # F1 interface to DUs
    # e1Interface: "10.0.102.0/24"  # E1 interface between CU-CP and CU-UP  
    # n2Interface: "10.0.103.0/24"  # N2 interface to 5GC (AMF)
    # n3Interface: "10.0.104.0/24"  # N3 interface to 5GC (UPF)

  # Extended O-RAN specific configuration (would be part of spec in real implementation)
  # oranConfig:
  #   cuType: "split"              # Split CU (separate CU-CP and CU-UP)
  #   plmnId: "00101"             # Public Land Mobile Network ID
  #   trackingAreaCode: "1"        # Tracking Area Code
  #   cellConfiguration:
  #     - cellId: "001"
  #       frequency: "3500MHz"     # 5G NR frequency band
  #       bandwidth: "100MHz"      # Channel bandwidth
  #       maxUeConnections: 1000   # Maximum connected UEs
  #       slices:                  # Network slicing configuration
  #         - sst: 1               # Slice/Service Type (eMBB)
  #           sd: "000001"         # Slice Differentiator
  #         - sst: 2               # URLLC slice
  #           sd: "000002"
  #   interfaces:
  #     f1:
  #       enabled: true
  #       ipAddress: "10.0.101.10"
  #       port: 38472
  #     e1:
  #       enabled: true  
  #       ipAddress: "10.0.102.10"
  #       port: 38462
  #     n2:
  #       enabled: true
  #       ipAddress: "10.0.103.10" 
  #       port: 38412
  #   security:
  #     encryption: "aes256"
  #     authentication: "sha256"
  #     certificateRef: "oran-cu-cert"

status:
  # Status will be populated by the O2 IMS controller
  observedGeneration: 0
  phase: ""
  conditions: []
  provisionedResources: {}