---
apiVersion: v1
kind: Namespace
metadata:
  name: focom-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oclouds.focom.nephio.org
spec:
  group: focom.nephio.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              endpoint:
                type: string
              secretRef:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
          status:
            type: object
            properties:
              ready:
                type: boolean
              phase:
                type: string
  scope: Namespaced
  names:
    plural: oclouds
    singular: ocloud
    kind: OCloud
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templateinfos.focom.nephio.org
spec:
  group: focom.nephio.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              template:
                type: string
              parameters:
                type: object
                x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              ready:
                type: boolean
  scope: Namespaced
  names:
    plural: templateinfos
    singular: templateinfo
    kind: TemplateInfo
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: focomprovisioningrequests.focom.nephio.org
spec:
  group: focom.nephio.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              ocloudRef:
                type: object
                properties:
                  name:
                    type: string
              templateRef:
                type: object
                properties:
                  name:
                    type: string
              parameters:
                type: object
                x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              ready:
                type: boolean
              phase:
                type: string
              provisioningRequestName:
                type: string
              packageVariants:
                type: array
                items:
                  type: string
              cluster:
                type: string
  scope: Namespaced
  names:
    plural: focomprovisioningrequests
    singular: focomprovisioningrequest
    kind: FocomProvisioningRequest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: focom-controller
  namespace: focom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focom-controller
  template:
    metadata:
      labels:
        app: focom-controller
    spec:
      serviceAccountName: focom-controller
      containers:
      - name: controller
        image: busybox:latest
        command: ["sh", "-c", "echo 'FoCoM controller placeholder running'; sleep infinity"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: focom-controller
  namespace: focom-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: focom-controller
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["focom.nephio.org"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["porch.kpt.dev"]
  resources: ["packagerevisions", "packagevariants"]
  verbs: ["*"]
- apiGroups: ["workload.nephio.org"]
  resources: ["clusters"]
  verbs: ["*"]
- apiGroups: ["o2ims.nephio.org"]
  resources: ["provisioningrequests"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: focom-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: focom-controller
subjects:
- kind: ServiceAccount
  name: focom-controller
  namespace: focom-system