apiVersion: v1
kind: Namespace
metadata:
  name: config-management-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: root-reconciler
  namespace: config-management-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: root-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: root-reconciler
  namespace: config-management-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-reconciler
  namespace: config-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: root-reconciler
  template:
    metadata:
      labels:
        app: root-reconciler
    spec:
      serviceAccountName: root-reconciler
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.6.4
        args:
        - --repo=http://172.16.0.78:8888/admin1/edge1-config
        - --branch=main
        - --depth=1
        - --period=30s
        - --root=/repo
        - --username=admin1
        - --password=admin123
        volumeMounts:
        - name: repo
          mountPath: /repo
      - name: reconciler
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            echo "Sync check at $(date)"
            # Placeholder for actual sync logic
            sleep 60
          done
        volumeMounts:
        - name: repo
          mountPath: /repo
      volumes:
      - name: repo
        emptyDir: {}