apiVersion: v1
kind: ConfigMap
metadata:
  name: expectation-config
  namespace: default
  annotations:
    config.kubernetes.io/local-config: "true"
    config.kubernetes.io/function: |
      container:
        image: expectation-to-krm:latest
    expectation.28312.3gpp.org/input: "true"
data:
  expectation.json: |
    {
      "expectationId": "sample-edge-expectation-001",
      "expectationObject": {
        "objectType": "O-RAN-DU",
        "objectInstance": "sample-du-cluster-01",
        "objectParameters": {
          "deployment": "edge",
          "location": "sample-cell-site-001",
          "resources": {
            "cpu": "2",
            "memory": "4Gi",
            "storage": "50Gi"
          }
        }
      },
      "expectationTarget": [
        {
          "targetName": "user-plane-latency",
          "targetCondition": "LessThanOrEqual",
          "targetValue": 2,
          "targetContexts": [
            {
              "contextAttribute": "measurement-unit",
              "contextCondition": "Equal",
              "contextValueType": "string",
              "contextValue": "milliseconds"
            }
          ]
        }
      ],
      "expectationContext": {
        "timeWindow": "1hour",
        "o2imsProvider": "sample-o2ims-001"
      }
    }