# This rule is not used by the project nephio-intent-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over tna.tna.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nephio-intent-operator
    app.kubernetes.io/managed-by: kustomize
  name: intentdeployment-admin-role
rules:
- apiGroups:
  - tna.tna.ai
  resources:
  - intentdeployments
  verbs:
  - '*'
- apiGroups:
  - tna.tna.ai
  resources:
  - intentdeployments/status
  verbs:
  - get
