apiVersion: v1
kind: ConfigMap
metadata:
  name: embb-edge3-001-monitoring
  namespace: ran-workloads
  labels:
    target-site: edge3
    generated-by: render-krm
    generated-at: "2025-09-13T07:11:25Z"
  annotations:
    intent.nephio.org/expectation-id: "embb-edge3-001"
    intent.nephio.org/expectation-type: "ServicePerformance"
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "intent_rules.yml"

    scrape_configs:
      - job_name: 'intent-metrics'
        static_configs:
          - targets: ['embb-edge3-001:8080']
        metrics_path: /metrics
        scrape_interval: 10s

  intent_rules.yml: |
    groups:
    - name: intent.rules
      rules:
      - alert: IntentSLOViolation
        expr: intent_slo_compliance{intent_id="embb-edge3-001"} < 0.95
        for: 30s
        labels:
          severity: critical
          target_site: edge3
        annotations:
          summary: "Intent SLO violation detected"
          description: "Intent {{ $labels.intent_id }} on {{ $labels.target_site }} has SLO compliance below 95%"
      - alert: LatencyThresholdExceeded
        expr: intent_latency_p99{intent_id="embb-edge3-001"} > 10
        for: 10s
        labels:
          severity: warning
          target_site: edge3
        annotations:
          summary: "Latency threshold exceeded"
          description: "99th percentile latency for intent {{ $labels.intent_id }} exceeded 10ms"
