apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: edge2-rootsync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: http://172.16.0.78:30000/admin1/edge2-config  # VM-1 Gitea repository
    branch: main
    dir: /  # Root directory of the repository
    auth: token
    secretRef:
      name: gitea-token
    period: 30s  # Sync interval

  # Override settings for specific namespaces
  override:
    namespaceStrategy: explicit
    namespaces:
      - oran-nfs
      - oran-services
      - monitoring

  # Resource management settings
  resourceManagement:
    mode: delete  # Delete resources not in Git

---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-token
  namespace: config-management-system
type: Opaque
stringData:
  token: "1b5ea0b27add59e71980ba3f7612a3bfed1487b7"  # Gitea access token
  username: "admin1"
---
# ClusterRoleBinding for Config Sync to manage resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge2-rootsync-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: root-reconciler-edge2-rootsync
    namespace: config-management-system
---
# NetworkPolicy to allow Config Sync to reach Gitea
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gitea-sync
  namespace: config-management-system
spec:
  podSelector:
    matchLabels:
      app: git-sync
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 172.16.0.0/16  # Allow access to VM-1 network
      ports:
        - protocol: TCP
          port: 30000  # Gitea port
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 53  # DNS
        - protocol: UDP
          port: 53  # DNS