# Config Sync Operator for GitOps automation
apiVersion: v1
kind: Namespace
metadata:
  name: config-management-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-management-operator
  namespace: config-management-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-management-operator
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-management-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: config-management-operator
subjects:
- kind: ServiceAccount
  name: config-management-operator
  namespace: config-management-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-management-operator
  namespace: config-management-system
data:
  config: |
    apiVersion: configmanagement.gke.io/v1
    kind: ConfigManagement
    metadata:
      name: config-management
    spec:
      git:
        syncRepo: http://172.16.4.45:3000/gitea/nephio-demo
        syncBranch: main
        secretType: none
        policyDir: gitops/edge3-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-management-operator
  namespace: config-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config-management-operator
  template:
    metadata:
      labels:
        name: config-management-operator
    spec:
      serviceAccountName: config-management-operator
      containers:
      - name: manager
        image: gcr.io/config-management-release/config-management-operator:20241119-1729088659
        ports:
        - containerPort: 8080
          name: metrics
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "config-management-operator"