apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: measurementjobs.o2ims.oran.org
spec:
  group: o2ims.oran.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetEndpoint:
                type: string
                description: The endpoint to scrape metrics from
              scrapeInterval:
                type: string
                description: How often to scrape the endpoint (e.g., 30s, 1m)
                default: "30s"
              metricsPath:
                type: string
                description: Path for metrics endpoint
                default: "/metrics"
              reportTo:
                type: string
                description: O2IMS endpoint to report metrics to
              selector:
                type: object
                properties:
                  service:
                    type: string
                  namespace:
                    type: string
                  port:
                    type: string
              parser:
                type: string
                description: Parser type for metrics (json, prometheus)
                default: "json"
            required:
            - targetEndpoint
            - reportTo
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Ready", "Failed"]
              lastScrapeTime:
                type: string
              lastScrapeStatus:
                type: string
              metricsCount:
                type: integer
              message:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Target
      type: string
      jsonPath: .spec.targetEndpoint
    - name: Last Scrape
      type: string
      jsonPath: .status.lastScrapeTime
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: measurementjobs
    singular: measurementjob
    kind: MeasurementJob
    shortNames:
    - mj