apiVersion: o2ims.provisioning.oran.org/v1alpha1
kind: ProvisioningRequest
metadata:
  name: edge-5g-deployment
  namespace: o2ims
  labels:
    workload.nephio.org/type: 5g-ran
    o2ims.oran.org/priority: high
  annotations:
    o2ims.oran.org/request-id: "req-5g-001"
    o2ims.oran.org/requester: "smo-controller"
spec:
  # Request description
  description: "Deploy 5G RAN (DU/CU) workload on edge O-Cloud"
  
  # Reference to the template
  template:
    name: edge-5g-template
    namespace: o2ims
    version: "1.0.0"
  
  # Target cluster reference
  cluster:
    name: edge-ocloud
    namespace: o2ims
  
  # Override template parameters
  parameters:
    namespace: "ran-workloads"
    du_replicas: 3
    cu_replicas: 2
    cpu_request: "2"
    memory_request: "4Gi"
    cpu_limit: "4"
    memory_limit: "8Gi"
    enable_gpu: false
    storage_class: "fast-ssd"
    network_config:
      f1_interface: "eth1"
      e1_interface: "eth2"
      x2_interface: "eth3"
      mtu: 9000
      enable_sr_iov: true
  
  # Workload specification
  workload:
    name: "5g-ran-du-cu-workload"
    type: "5g-ran-du-cu"
    version: "1.0.0"
    labels:
      app: "5g-ran"
      component: "du-cu"
      vendor: "nephio"
  
  # Deployment configuration
  deployment:
    strategy: "RollingUpdate"
    timeout: 600
    retries: 3
    rollbackOnFailure: true
  
  # Resource requirements
  resources:
    requests:
      cpu: "10"
      memory: "20Gi"
      storage: "100Gi"
    limits:
      cpu: "20"
      memory: "40Gi"
      storage: "200Gi"
  
  # Network requirements
  network:
    multus:
      enabled: true
    sriov:
      enabled: true
      interfaces:
        - name: "f1"
          vfCount: 4
        - name: "e1"
          vfCount: 2
  
  # Security requirements
  security:
    podSecurityPolicy:
      enabled: true
      name: "restricted"
    networkPolicy:
      enabled: true
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  name: ran-workloads
      egress:
        - to:
            - namespaceSelector:
                matchLabels:
                  name: ran-workloads
  
  # Monitoring configuration
  monitoring:
    enabled: true
    metrics:
      interval: "30s"
      path: "/metrics"
      port: 9090
    alerts:
      - name: "high-cpu-usage"
        expr: "cpu_usage > 80"
        severity: "warning"
      - name: "pod-restart"
        expr: "pod_restarts > 5"
        severity: "critical"
  
  # SLA requirements
  sla:
    availability: "99.9"
    latency:
      p95: "10ms"
      p99: "20ms"
    throughput:
      minimum: "10Gbps"
  
  # Lifecycle hooks
  hooks:
    preProvision:
      - name: "validate-cluster-capacity"
        timeout: 60
    postProvision:
      - name: "run-smoke-tests"
        timeout: 120
      - name: "configure-monitoring"
        timeout: 60
    preTerminate:
      - name: "backup-configuration"
        timeout: 60
  
  # Approval workflow
  approval:
    required: false
    approvers:
      - "platform-team"
      - "network-team"
  
  # Priority and scheduling
  priority: 100
  schedulingPolicy: "immediate"
  
  # Maintenance window
  maintenanceWindow:
    enabled: false
    schedule: "0 2 * * SUN"
    duration: "4h"