#!/bin/bash
# Generate pocket Q&A reference for summit

echo "# Pocket Q&A Reference"
echo ""
echo "**Quick reference for O-RAN Intent-to-O2 Demo**"
echo ""
echo "## Technical Q&A"
echo ""
echo "### Q: What O-RAN standards does this implement?"
echo "**A:** TMF921 Intent Management, 3GPP TS 28.312 Expectations, O-RAN O2 IMS, and WG11 Security frameworks."
echo ""
echo "### Q: What are the key ports and IPs?"
echo "**A:** "
echo "- VM-2 Edge1: 172.16.4.45 (K8s API: 6443, HTTP: 31080, O2IMS: 31280)"
echo "- VM-1 (Integrated) LLM: 172.16.0.78:8888"  
echo "- VM-4 Edge2: TBD (same port layout as VM-2)"
echo ""
echo "### Q: How is multi-site deployment achieved?"
echo "**A:** Intent.targetSite field routes to edge1, edge2, or both via KRM rendering and GitOps RootSync reconciliation."
echo ""
echo "## Demo Troubleshooting"
echo ""
echo "### Q: Demo fails at LLM step?"
echo "**A:** Check VM-1 (Integrated) connectivity. If down: restart llm-adapter service"
echo ""
echo "### Q: Edge cluster unreachable?"  
echo "**A:** Verify K8s API at port 6443. If timeout: restart kubelet"
echo ""
echo "## Command Reference"
echo ""
echo "### Emergency Commands"
echo "\`\`\`bash"
echo "# Quick health check"
echo "curl http://172.16.4.45:31080/health"
echo "curl http://172.16.0.78:8888/health"
echo ""
echo "# Run demo"  
echo "./scripts/demo_llm.sh --target edge1"
echo "\`\`\`"
echo ""
echo "---"
echo "**Generated:** $(date)"
