# Prometheus Configuration for VM-1 SMO Monitoring
# Monitors Edge-1 (172.16.4.45), Edge-2 (172.16.4.176), and local services

global:
  scrapeInterval: 30s
  evaluationInterval: 30s
  externalLabels:
    cluster: 'smo-vm1'
    region: 'central'
    role: 'orchestrator'

prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.40.0

  retention: "30d"
  retentionSize: "50GB"

  nodePort: 31090

  # External targets for edge sites
  additionalScrapeConfigs: |
    # Edge-1 (VM-2) Kubernetes API Server
    - job_name: 'edge1-kubernetes-api'
      static_configs:
        - targets: ['172.16.4.45:6443']
      scheme: https
      tls_config:
        insecure_skip_verify: true
      basic_auth:
        username: 'prometheus'
        password: 'monitoring123'
      metrics_path: '/metrics'
      scrape_interval: 30s
      relabel_configs:
        - target_label: site
          replacement: 'edge1'
        - target_label: cluster
          replacement: 'edge1'

    # Edge-2 (VM-4) Kubernetes API Server
    - job_name: 'edge2-kubernetes-api'
      static_configs:
        - targets: ['172.16.4.176:6443']
      scheme: https
      tls_config:
        insecure_skip_verify: true
      basic_auth:
        username: 'prometheus'
        password: 'monitoring123'
      metrics_path: '/metrics'
      scrape_interval: 30s
      relabel_configs:
        - target_label: site
          replacement: 'edge2'
        - target_label: cluster
          replacement: 'edge2'

    # Edge-1 SLO Service
    - job_name: 'edge1-slo-service'
      static_configs:
        - targets: ['172.16.4.45:30090']
      metrics_path: '/metrics'
      scrape_interval: 15s
      relabel_configs:
        - target_label: site
          replacement: 'edge1'
        - target_label: service
          replacement: 'slo-monitoring'

    # Edge-2 SLO Service
    - job_name: 'edge2-slo-service'
      static_configs:
        - targets: ['172.16.4.176:30090']
      metrics_path: '/metrics'
      scrape_interval: 15s
      relabel_configs:
        - target_label: site
          replacement: 'edge2'
        - target_label: service
          replacement: 'slo-monitoring'

    # Edge-1 O2IMS Service
    - job_name: 'edge1-o2ims'
      static_configs:
        - targets: ['172.16.4.45:31280']
      metrics_path: '/metrics'
      scrape_interval: 30s
      relabel_configs:
        - target_label: site
          replacement: 'edge1'
        - target_label: service
          replacement: 'o2ims'

    # Edge-2 O2IMS Service
    - job_name: 'edge2-o2ims'
      static_configs:
        - targets: ['172.16.4.176:31280']
      metrics_path: '/metrics'
      scrape_interval: 30s
      relabel_configs:
        - target_label: site
          replacement: 'edge2'
        - target_label: service
          replacement: 'o2ims'

    # GitOps Sync Status (local VM-1)
    - job_name: 'gitops-sync-status'
      static_configs:
        - targets: ['localhost:8888']
      metrics_path: '/api/v1/repos/admin1/edge1-config/git/commits'
      scrape_interval: 60s
      relabel_configs:
        - target_label: service
          replacement: 'gitops'
        - target_label: component
          replacement: 'gitea'

    # VM-1 Local Node Exporter
    - job_name: 'vm1-node-exporter'
      static_configs:
        - targets: ['localhost:9100']
      relabel_configs:
        - target_label: site
          replacement: 'vm1'
        - target_label: role
          replacement: 'orchestrator'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "/etc/prometheus/rules/*.yml"

serverFiles:
  alerts:
    groups:
      - name: multi-site-slo-alerts
        interval: 30s
        rules:
          - alert: EdgeSiteDown
            expr: up{job=~"edge[12]-.*"} == 0
            for: 2m
            labels:
              severity: critical
              component: infrastructure
            annotations:
              summary: "Edge site {{ $labels.site }} is unreachable"
              description: "Cannot reach {{ $labels.job }} for more than 2 minutes"

          - alert: HighErrorRateMultiSite
            expr: |
              (
                sum(rate(http_requests_total{status=~"5.."}[5m])) by (site)
                /
                sum(rate(http_requests_total[5m])) by (site)
              ) > 0.05
            for: 2m
            labels:
              severity: warning
              component: application
            annotations:
              summary: "High error rate on {{ $labels.site }}"
              description: "Error rate is {{ $value | humanizePercentage }} on {{ $labels.site }}"

          - alert: O2IMSServiceDown
            expr: up{service="o2ims"} == 0
            for: 1m
            labels:
              severity: critical
              component: o2ims
            annotations:
              summary: "O2IMS service down on {{ $labels.site }}"
              description: "O2IMS service on {{ $labels.site }} has been down for more than 1 minute"

          - alert: SLOServiceDown
            expr: up{service="slo-monitoring"} == 0
            for: 1m
            labels:
              severity: critical
              component: slo
            annotations:
              summary: "SLO monitoring service down on {{ $labels.site }}"
              description: "SLO monitoring service on {{ $labels.site }} has been down for more than 1 minute"

          - alert: GitOpsSyncFailure
            expr: increase(gitops_sync_failures_total[5m]) > 0
            for: 2m
            labels:
              severity: warning
              component: gitops
            annotations:
              summary: "GitOps sync failures detected"
              description: "GitOps sync has failed {{ $value }} times in the last 5 minutes"

pushgateway:
  enabled: true
  nodePort: 31091

nodeExporter:
  enabled: true
  nodePort: 31092

# Storage configuration
persistence:
  enabled: true
  size: 50Gi
  storageClass: "standard"