apiVersion: v1
kind: Service
metadata:
  name: edge2-lb
  namespace: oran-services
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.16.0.90
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: oran-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
    - name: o2ims
      port: 30205
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lb-config
  namespace: oran-services
data:
  backends.conf: |
    # Edge2 Load Balancer Backend Configuration
    upstream oran_backend {
      server 10.244.0.10:8080 weight=1;
      server 10.244.0.11:8080 weight=1;
      keepalive 32;
    }

    upstream metrics_backend {
      server 10.244.0.20:9090 weight=1;
      keepalive 16;
    }