apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: oran-services
  labels:
    app: service-discovery
    component: core
spec:
  type: ClusterIP
  selector:
    app: service-registry
  ports:
    - name: http
      port: 8500
      targetPort: 8500
      protocol: TCP
    - name: grpc
      port: 8502
      targetPort: 8502
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-discovery-config
  namespace: oran-services
data:
  config.yaml: |
    discovery:
      enabled: true
      site: edge2
      refresh_interval: 30s
      health_check:
        interval: 10s
        timeout: 5s
      services:
        - name: o2ims
          port: 8080
          health: /health
        - name: metrics-api
          port: 9090
          health: /metrics
        - name: slo-gateway
          port: 8081
          health: /api/v1/health