# Prometheus Remote Write Configuration v1.2.0 for Edge Sites
# Central monitoring aggregation to VM-1 orchestrator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-remote-write-config
  namespace: monitoring
data:
  remote_write.yml: |
    remote_write:
      - url: http://172.16.4.45:9090/api/v1/write  # VM-1 orchestrator Prometheus
        queue_config:
          capacity: 10000
          max_shards: 10
          min_shards: 1
          max_samples_per_send: 1000
          batch_send_deadline: 5s
          min_backoff: 30ms
          max_backoff: 100ms
        write_relabel_configs:
          # Add edge site label
          - source_labels: [__name__]
            regex: '.*'
            target_label: edge_site
            replacement: 'EDGE_SITE_NAME'  # Will be replaced per site
          # Add cluster label
          - source_labels: [__name__]
            regex: '.*'
            target_label: cluster
            replacement: 'EDGE_CLUSTER_NAME'  # Will be replaced per site
          # Add version label
          - source_labels: [__name__]
            regex: '.*'
            target_label: version
            replacement: 'v1.2.0'
        metadata_config:
          send: true
          send_interval: 1m
        retry_on_http_429: true
