name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Free up disk space
        run: |
          # Remove some unused packages to free up space
          sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' '^mongodb-.*' '^mysql-.*' azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e-minimal

      - name: Cleanup on failure
        if: failure()
        run: |
          echo "Cleaning up Kind cluster on failure..."
          kind get clusters || true
          kubectl cluster-info || true
          kubectl get nodes || true
          make cleanup-test-e2e || true
