apiVersion: apps/v1
kind: Deployment
metadata:
  name: slo-exporter
  namespace: edge2-workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slo-exporter
  template:
    metadata:
      labels:
        app: slo-exporter
    spec:
      containers:
      - name: exporter
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: scripts
          mountPath: /docker-entrypoint.d
      volumes:
      - name: html
        configMap:
          name: slo-html
      - name: scripts
        configMap:
          name: slo-scripts
          defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-html
  namespace: edge2-workloads
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Edge2 SLO Exporter</title></head>
    <body>
      <h1>Edge2 SLO Metrics</h1>
      <p>Site: edge2</p>
      <p>Status: operational</p>
      <p>Response time: <span id="time">5</span>ms</p>
      <script>
        setInterval(() => {
          document.getElementById('time').innerText = Math.floor(Math.random() * 20) + 1;
        }, 1000);
      </script>
    </body>
    </html>
  metrics: |
    {"latency_p95_ms": 15, "success_rate": 0.998, "throughput_rps": 250}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-scripts
  namespace: edge2-workloads
data:
  50-generate-metrics.sh: |
    #!/bin/sh
    while true; do
      LATENCY=$((RANDOM % 30 + 5))
      SUCCESS=$(awk 'BEGIN{printf "%.3f", 0.990 + (rand() * 0.01)}')
      RPS=$((RANDOM % 100 + 200))
      echo "{\"latency_p95_ms\": $LATENCY, \"success_rate\": $SUCCESS, \"throughput_rps\": $RPS, \"timestamp\": \"$(date -Iseconds)\"}" > /usr/share/nginx/html/slo.json
      sleep 5
    done &
---
apiVersion: v1
kind: Service
metadata:
  name: slo-exporter-service
  namespace: edge2-workloads
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31080
  selector:
    app: slo-exporter